services:
  app:
    build: ./backend
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - laravel
    expose:
      - "9000" 
    user: "www-data"

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
    networks:
      - laravel
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 5s
    volumes:
      - mysql_data:/var/lib/mysql

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "9000:9000"  # Permitindo acesso direto pela porta 9000 também
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  frontend:
    build: ./frontend
    container_name: evento-frontend
    restart: unless-stopped
    working_dir: /app
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules 
    ports:
      - "5173:5173"
    depends_on:
      - app

networks:
  laravel:

volumes:
  mysql_data:
